### ISSUE TITLE
Copy certificate bundle without need root user key creation

### ISSUE THREAD

**Issue by A-Beck** [RedHatOfficial/ansible-role-redhat_satellite6_capsule_installation#3]
Currently, to copy certificates from the satellite server to the capsule server, a root key is generated on the satellite server and distributed to the capsule servers.

```
- block:
    - name: Satelllite | Capsule | Certificate Bundle | Create Capsule Certificates Directory on Satellite Server
      file:
        path: "{{ satellite_capsule_server_certs_dir }}"
        state: directory
        mode: 0700
    
    - name: Satelllite | Capsule | Certificate Bundle | Create ssh key for root user on Satellite Server
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
    
    - name: Satelllite | Capsule | Certificate Bundle | Get Satellite Server root user public key
      slurp:
        path: "/root/.ssh/id_rsa.pub"
      register: satellite_server_root_public_key
  delegate_to: "{{ satellite_server_host }}"
  run_once: true

- name: Satelllite | Capsule | Certificate Bundle | Add Satellite Server root user public key to root user on Capsule Server
  authorized_key:
    user: root
    state: present
    key: "{{ satellite_server_root_public_key.content | b64decode }}"
```

This should be change so that content is not directly synchronized from the satellite server to the capsule server. Some approaches we could take:
- slurp the certificate file with the slurp module, and put it on the capsule server with the copy module
- Sync satellite --> ansible host, then sync ansible --> capsule server
